/**
 * Unit and integration tests for workflow.ts
 *
 * Pure functions are tested directly.
 * Tauri-dependent functions are tested with mock context.
 */

import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import {
  setupMockTauri,
  type MockTauriContext,
} from "@symbiosis-lab/moss-api/testing";

// workflow.ts no longer imports from utils — no mock needed

import {
  WORKFLOW_TEMPLATE,
  generateWorkflowContent,
  createWorkflowFile,
  workflowExists,
} from "../workflow";

describe("WORKFLOW_TEMPLATE", () => {
  it("contains the branch placeholder", () => {
    expect(WORKFLOW_TEMPLATE).toContain("BRANCH_PLACEHOLDER");
  });

  it("includes required GitHub Actions setup", () => {
    expect(WORKFLOW_TEMPLATE).toContain("actions/checkout@v4");
    expect(WORKFLOW_TEMPLATE).toContain("actions/configure-pages@v4");
    expect(WORKFLOW_TEMPLATE).toContain("actions/upload-pages-artifact@v3");
    expect(WORKFLOW_TEMPLATE).toContain("actions/deploy-pages@v4");
  });

  it("includes correct permissions", () => {
    expect(WORKFLOW_TEMPLATE).toContain("contents: read");
    expect(WORKFLOW_TEMPLATE).toContain("pages: write");
    expect(WORKFLOW_TEMPLATE).toContain("id-token: write");
  });

  it("references .moss/build/current as the upload path (current generation symlink)", () => {
    expect(WORKFLOW_TEMPLATE).toContain("path: .moss/build/current");
    // Must NOT reference the now-empty legacy .moss/build/site path
    expect(WORKFLOW_TEMPLATE).not.toContain("path: .moss/build/site");
  });

  it("includes workflow_dispatch trigger", () => {
    expect(WORKFLOW_TEMPLATE).toContain("workflow_dispatch:");
  });
});

describe("generateWorkflowContent", () => {
  it("replaces placeholder with main branch", () => {
    const result = generateWorkflowContent("main");
    expect(result).toContain("branches: [main]");
    expect(result).not.toContain("BRANCH_PLACEHOLDER");
  });

  it("replaces placeholder with master branch", () => {
    const result = generateWorkflowContent("master");
    expect(result).toContain("branches: [master]");
    expect(result).not.toContain("BRANCH_PLACEHOLDER");
  });

  it("replaces placeholder with custom branch", () => {
    const result = generateWorkflowContent("develop");
    expect(result).toContain("branches: [develop]");
    expect(result).not.toContain("BRANCH_PLACEHOLDER");
  });

  it("generates valid YAML structure", () => {
    const result = generateWorkflowContent("main");

    // Check for valid YAML key structure
    expect(result).toContain("name: Deploy to GitHub Pages");
    expect(result).toContain("on:");
    expect(result).toContain("permissions:");
    expect(result).toContain("jobs:");
    expect(result).toContain("deploy:");
    expect(result).toContain("steps:");
  });

  it("preserves the moss header comment", () => {
    const result = generateWorkflowContent("main");
    expect(result).toContain("# moss GitHub Pages Deployment");
    expect(result).toContain("Generated by moss");
  });
});

// ============================================================================
// Integration tests for Tauri-dependent functions
// ============================================================================

describe("createWorkflowFile", () => {
  let ctx: MockTauriContext;
  const projectPath = "/test/project";

  beforeEach(() => {
    ctx = setupMockTauri({ projectPath });
    vi.clearAllMocks();
  });

  afterEach(() => {
    ctx.cleanup();
  });

  it("creates workflow file with correct content", async () => {
    await createWorkflowFile("main");

    const file = ctx.filesystem.getFile(`${projectPath}/.github/workflows/moss-deploy.yml`);
    expect(file?.content).toContain("branches: [main]");
    expect(file?.content).toContain("Deploy to GitHub Pages");
  });

  it("uses custom branch name in workflow", async () => {
    await createWorkflowFile("develop");

    const file = ctx.filesystem.getFile(`${projectPath}/.github/workflows/moss-deploy.yml`);
    expect(file?.content).toContain("branches: [develop]");
  });
});

describe("workflowExists", () => {
  let ctx: MockTauriContext;
  const projectPath = "/test/project";

  beforeEach(() => {
    ctx = setupMockTauri({ projectPath });
  });

  afterEach(() => {
    ctx.cleanup();
  });

  it("returns true when workflow file exists", async () => {
    ctx.filesystem.setFile(`${projectPath}/.github/workflows/moss-deploy.yml`, "name: Test");

    const result = await workflowExists();
    expect(result).toBe(true);
  });

  it("returns false when workflow file does not exist", async () => {
    const result = await workflowExists();
    expect(result).toBe(false);
  });
});
