/**
 * GitHub Actions workflow template and creation
 */

import { writeFile, fileExists } from "@symbiosis-lab/moss-api";

/**
 * GitHub Actions workflow template for deploying to GitHub Pages
 * This is extracted from the original deploy.rs
 */
export const WORKFLOW_TEMPLATE = `# moss GitHub Pages Deployment
# This workflow deploys your pre-built site from .moss/build/current/ to GitHub Pages
# Generated by moss - https://mosspub.com

name: Deploy to GitHub Pages

on:
  push:
    branches: [BRANCH_PLACEHOLDER]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .moss/build/current

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
`;

/**
 * Generate the workflow content with the correct branch
 */
export function generateWorkflowContent(branch: string): string {
  return WORKFLOW_TEMPLATE.replace("BRANCH_PLACEHOLDER", branch);
}

/**
 * Create the GitHub Actions workflow file
 */
export async function createWorkflowFile(branch: string): Promise<void> {
  console.log("   Creating .github/workflows/moss-deploy.yml...");

  const content = generateWorkflowContent(branch);

  await writeFile(".github/workflows/moss-deploy.yml", content);

  console.log("   Workflow file created");
}

/**
 * Check if the workflow file already exists
 */
export async function workflowExists(): Promise<boolean> {
  return fileExists(".github/workflows/moss-deploy.yml");
}
